[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
solc = "0.8.20"

[rpc_endpoints]
bsc_testnet = "https://bsc-testnet.publicnode.com"
bsc = "https://bsc.publicnode.com"
base_sepolia = "https://sepolia.base.org"
sepolia = "https://sepolia.gateway.tenderly.co"
